apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-disruptionbudget
  labels:
{{ include "camp-dns-efk.labels" . | indent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: unbound
{{ include "camp-dns-efk.labels" . | indent 6 }}
