apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-elasticsearch-configmap
  labels:
{{ include "camp-dns-efk.labels" . | indent 4 }}
  creationtimestamp: "2019-09-01t19:08:57z"
data:
  ES_JAVA_OPTS: "-Xms{{ .Values.elasticsearch.memory }} -Xmx{{ .Values.elasticsearch.memory }}"
  bootstrap.memory_lock: "true"
  discovery.type: "single-node"
  indices.query.bool.max_clause_count: "8192"
  search.max_buckets: "100000"
  action.destructive_requires_name: "true"
  network.host: "0.0.0.0"
  http.port: "9200"
