apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-elasticsearch-deployment
  labels:
{{ include "camp-dns-efk.labels" . | indent 4 }}
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-08-31T23:23:03Z"
  generation: 1

<<: &healthcheck-template
  httpGet:
    path: /
    port: elasticsearch
  initialDelaySeconds: 180
  timeoutSeconds: 2
  periodSeconds: 30

spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: elasticsearch
{{ include "camp-dns-efk.labels" . | indent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: elasticsearch
{{ include "camp-dns-efk.labels" . | indent 8 }}
    spec:
      initContainers:
        - name: change-pv-permission
          image: {{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}
          command: ["chown", "-R", "1000:1000", "/usr/share/elasticsearch/data"]
          volumeMounts:
            - name: esdata-pv
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: elasticsearch
          image: {{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}
          imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-elasticsearch-configmap
          ports:
            - name: elasticsearch
              containerPort: 9200
              protocol: TCP
          readinessProbe:
            <<: *healthcheck-template
            successThreshold: 1
            failureThreshold: 1
          livenessProbe:
            <<: *healthcheck-template
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: esdata-pv
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: esdata-pv
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-esdata-pvc

