apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
{{ include "camp-dns-efk.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: unbound
{{ include "camp-dns-efk.labels" . | indent 4 }}
  ports:
    - name: dns-udp
      targetPort: 53
      port: 53
      protocol: UDP
    - name: dns-tcp
      targetPort: 53
      port: 53
      protocol: TCP
  externalIPs:
{{ range .Values.unbound.listen }}
    - {{ . }}
{{ end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-elasticsearch
  labels:
{{ include "camp-dns-efk.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
{{ include "camp-dns-efk.labels" . | indent 4 }}
  ports:
    - name: elasticsearch
      targetPort: 9200
      port: 9200
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fluentd
  labels:
{{ include "camp-dns-efk.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: fluentd
{{ include "camp-dns-efk.labels" . | indent 4 }}
  ports:
    - name: syslog
      targetPort: 5140
      port: 514
      protocol: UDP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kibana
  labels:
{{ include "camp-dns-efk.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: kibana
{{ include "camp-dns-efk.labels" . | indent 4 }}
  ports:
    - name: http
      targetPort: 5601
      port: 5601
      protocol: TCP
  externalIPs:
    - {{ .Values.kibana.listen }}
